In [32]:
import numpy as np

# Basic arrays

## Array of zeroes

In [41]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Array of ones

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Array of pre-determined number

In [43]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## Identity matrix

In [44]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random numbers between 0-1

In [50]:
np.random.random((3,3))

array([[0.60611761, 0.1093525 , 0.53552953],
       [0.24203282, 0.25510387, 0.97406449],
       [0.30940786, 0.6148389 , 0.64019599]])

## Random numbers from specified range

In [51]:
np.random.randint(1,10,(3,3))

array([[1, 5, 6],
       [7, 3, 3],
       [5, 2, 2]])

## Evenly spaced numbers in array

In [52]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Set markers in array

In [53]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

## Convert list to numpy array and vice versa

In [59]:
exampleList = [1,2,3,4]
exampleArray = np.array(exampleList)

In [192]:
x = np.array([1,2,3])
list(x)

[1, 2, 3]

## Tying it all together

### Create a 3x4 matrix of numbers using 0-11

In [57]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Array attributes

## Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the attributes of the array.

In [33]:
x = np.array([1,7,13,105])

In [40]:
def checkAttributes(array):
    size = array.size
    shape = array.shape
    memory = array.nbytes
    dtype = array.dtype
    print(size,shape,memory,dtype, sep='\n')

checkAttributes(x)

4
(4,)
16
int32


## Force-set the ntype of a numpy array

In [60]:
array = np.arange(0,5)
print(array)
array = array.astype('float64')
print(array)
array=array.astype('bool')
print(array)
array=array.astype('str')
print(array)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[False  True  True  True  True]
['False' 'True' 'True' 'True' 'True']


# Basic array operations

## Basic mathematical functions

In [62]:
x = np.linspace(0,1,10)
np.sin(x)

array([0.        , 0.11088263, 0.22039774, 0.3271947 , 0.42995636,
       0.52741539, 0.6183698 , 0.70169788, 0.77637192, 0.84147098])

In [63]:
np.exp(x)

array([1.        , 1.11751907, 1.24884887, 1.39561243, 1.5596235 ,
       1.742909  , 1.94773404, 2.17662993, 2.43242545, 2.71828183])

In [64]:
np.exp2(x)

array([1.        , 1.08005974, 1.16652904, 1.25992105, 1.36079   ,
       1.46973449, 1.58740105, 1.71448797, 1.85174942, 2.        ])

# Aggregation functions

## Basic reduction/accumulation

In [66]:
x = np.linspace(1,5,5)
print(x)

[1. 2. 3. 4. 5.]


## Basic statistic aggregations

In [67]:
np.add.reduce(x)

15.0

In [69]:
np.multiply.reduce(x)

120.0

In [70]:
np.add.accumulate(x)

array([ 1.,  3.,  6., 10., 15.])

### Compute sum of elements

In [95]:
x = np.random.randint(1,100,(3,3))
print(x)

[[51 50 53]
 [46  3  5]
 [75 31 25]]


In [96]:
np.nansum(x)

339

### Compute product of elements

In [97]:
np.nanprod(x)

110959948

### Compute mean of elements

In [98]:
np.nanmean(x)

37.666666666666664

### Compute median of elements

In [99]:
np.nanmedian(x)

46.0

### Compute std dev of elements

In [100]:
np.nanstd(x)

22.365648262955006

### Compute variance of elements

In [101]:
np.nanvar(x)

500.22222222222223

### Compute percentile of elements

In [105]:
np.percentile(x, 25)

25.0

### Compute max/min of elements

In [102]:
np.nanmin(x)

3

In [103]:
np.nanmax(x)

75

## Boolean aggregates

In [92]:
x = np.random.randint(0,2,(3,3))
print(x)

[[0 0 1]
 [1 0 1]
 [1 1 0]]


In [93]:
np.any(x)

True

In [94]:
np.all(x)

False

# Boolean masking

## Generating boolean masks from value arrays

In [157]:
x = np.array([1,2,3,4,5])
y = x**2

### Create a boolean array to check for values above 3

In [130]:
x>3

array([False, False, False,  True,  True])

### Create a boolean array to compare values between 2 seperate arrays

In [155]:
x == y

array([[ True,  True, False],
       [False, False, False],
       [ True, False, False]])

### Multiple conditions to check

In [158]:
(x>3) & (x<5)

array([False, False, False,  True, False])

In [162]:
(x>3) | (x<3)

array([ True,  True, False,  True,  True])

## Operating on boolean masks

In [143]:
y = np.random.randint(0,2,(3,3))
print(y)

[[1 0 1]
 [1 0 1]
 [0 0 1]]


In [147]:
yBool = y.astype(bool)
print(yBool)

[[ True False  True]
 [ True False  True]
 [False False  True]]


### Aggregate the number of true/false entries in entire array

In [150]:
np.sum(yBool)

5

### Aggregate the number of true/false entries along one axis (row/col)

In [151]:
np.sum(yBool,axis=0)
#check each col

array([2, 0, 3])

In [152]:
np.sum(yBool,axis=1)
#check each row

array([2, 2, 1])

### Quick check for any true/false

In [153]:
np.any(yBool)

True

## Selecting data from original value array based on boolean mask

### Original value array

In [164]:
x = np.random.randint(1,10,(3,3))
print(x)

[[4 2 7]
 [9 2 3]
 [7 8 9]]


### Boolean mask

In [171]:
xBool = x<4
print(xBool)

[[False  True False]
 [False  True  True]
 [False False False]]


### Display values that fit condition

In [172]:
xSelected = x[x<4]
print(xSelected)

[2 2 3]


## Examples

###  Write a NumPy program to test whether none of the elements of a given array is true/false

In [177]:
x = np.random.randint(0,2,(3,3))
print(x)

[[1 0 1]
 [0 1 1]
 [0 1 1]]


In [178]:
np.any(x==0)
#check for false

True

In [182]:
np.any(x!=0)
#check for true

True

### Write a NumPy program to return non-zero elements of a given array

In [184]:
x = np.random.randint(0,5,(3,3))
print(x)

[[0 1 1]
 [1 4 2]
 [2 4 4]]


In [185]:
x[x!=0]

array([1, 1, 1, 4, 2, 2, 4, 4])

### Write a NumPy program to return finite elements (not infinity or not a Number)

In [186]:
a = np.array([1, 0, np.nan, np.inf])
np.isfinite(a)

array([ True,  True, False, False])

### Write a NumPy program to test element-wise for positive or negative infinity.

In [188]:
a = np.array([1, 0, np.nan, np.inf])
np.isinf(a)

array([False, False, False,  True])

### Write a NumPy program to count element-wise for NaN of a given array

In [191]:
a = np.array([1, 0, np.nan, np.nan])
np.sum(np.isnan(a))

2

### Write a NumPy program to create a vector with values from 0 to 20 and select numbers between 9 and 15, and add a negative sign

In [195]:
x = np.random.randint(0,20,(3,3))
print(x)

[[17  6  3]
 [11  2 19]
 [15  6  2]]


In [199]:
xBool = (x>8) & (x<16)
print(xBool)

[[False False False]
 [ True False False]
 [ True False False]]


In [201]:
xSelected = x[xBool]
print(xSelected)

In [205]:
xSelected *= -1
print(xSelected)

[-11 -15]


### Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [206]:
x = np.arange(0,21)
x[(x >= 9) & (x <= 15)]*=-1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


# Set operations

## Making sets from arrays with repeated values

In [218]:
x = np.random.randint(0,6,(10,10))
print(x)

[[2 1 1 5 2 0 3 3 2 4]
 [5 4 2 0 0 2 3 5 1 0]
 [3 2 5 5 3 3 4 3 3 1]
 [2 2 4 1 1 5 0 3 2 0]
 [0 2 1 4 3 0 2 3 5 2]
 [1 2 1 4 5 4 1 4 0 2]
 [4 4 0 3 5 2 4 2 3 4]
 [3 3 1 0 5 0 1 4 5 5]
 [3 2 1 0 1 0 5 2 3 5]
 [2 2 5 5 1 5 3 5 5 0]]


In [221]:
xSet = np.unique(x)
print(xSet)

[0 1 2 3 4 5]


## Intersection between 2 arrays

In [224]:
array1 = np.random.randint(0,100,(10,20))
array2 = np.random.randint(0,10,(3,3))

In [225]:
np.intersect1d(array1, array2)

array([0, 2, 3, 5, 6])

## Check whether elements in one array is present in another

In [226]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
testArray = [0, 40]
print("Array holding values to be checked with: ", testArray)
print("Compare each element of array1 and array2")
print(np.in1d(array1, testArray))

Array1:  [ 0 10 20 40 60]
Array holding values to be checked with:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


## Find the set difference of two arrays

In [228]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])
np.setdiff1d(array1,array2)

array([10, 20, 60])

## Find the union of two arrays.

In [232]:
array1 = np.random.randint(0,10,(10,20))
array2 = np.random.randint(50,60,(3,3))
np.union1d(array1,array2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 50, 52, 53, 54, 55, 56, 57])

# Array indexing and slicing

## Specifying 1-D index

In [245]:
x = np.arange(1,10)
print(x)

x[-1]

[1 2 3 4 5 6 7 8 9]


9

## Specifying 2-D index

In [240]:
x = np.random.randint(0,10,(3,3))
print(x)

[[8 0 3]
 [3 3 2]
 [5 7 3]]


In [241]:
x[0,2] = 0
print(x)

[[8 0 0]
 [3 3 2]
 [5 7 3]]


## Appending new array

In [242]:
x=np.arange(0,5)
print(x)
y=np.arange(6,10)
np.append(x,y)

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 6, 7, 8, 9])

## Slicing 1-D index

In [248]:
x=np.arange(0,5)
x[3:5]

array([3, 4])

### Slicing with step specified

In [250]:
x=np.arange(0,10)
x[::2]

array([0, 2, 4, 6, 8])

## Slicing 2-D index

In [249]:
x = np.random.randint(0,10,(3,3))
print(x)

[[3 2 4]
 [2 0 7]
 [0 3 6]]


# Fancy indexing

## Accessing multiple values in 1-D

In [251]:
x = np.arange(0,20)
ind = [0,4,19]
x[ind]

array([ 0,  4, 19])

## Accessing multiple values in 2-D

In [259]:
x = np.arange(12).reshape((3, 4))
print(x)
row = [0,1,2]
col = [2,3,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [258]:
x[row,col]

array([2, 7, 7])

### Combine fancy with simple indexing

In [261]:
x = np.random.randint(0,10,(3,3))
print(x)

[[4 5 7]
 [5 7 2]
 [7 5 0]]


In [262]:
x[2,[0,2]]

array([7, 0])

### Combine fancy indexing with slicing

In [263]:
x[:1,[0,2]]

array([[4, 7]])

# Sorting

## Sorting according to axis

In [1]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [2]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [3]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Sorting the k-partition values

In [5]:
# result is a new array with the smallest K values to the left of the partition, 
# and the remaining values to the right, in arbitrary order
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])