In [1]:
import numpy as np
import math
import random
from scipy import linalg, optimize, integrate, special

# Dot product

## Dot product of 2 vectors

In [2]:
p = np.random.randint(0,9,(3))
q = np.random.randint(0,9,(3))
print(p,q,sep='\n')

[3 3 0]
[4 3 5]


In [3]:
np.dot(p,q)

21

## Multiplication of two similar shaped matrixes

In [4]:
p = np.random.randint(0,3,(3,3))
q = np.random.randint(0,3,(3,3))
print(p,q,sep='\n')

[[1 1 0]
 [2 0 1]
 [2 2 0]]
[[2 0 0]
 [1 2 1]
 [2 1 2]]


In [5]:
np.dot(p, q)

array([[3, 2, 1],
       [6, 1, 2],
       [6, 4, 2]])

## Multiplication of compatible but different shaped matrices

In [12]:
p = np.random.randint(0,3,(3,2))
q = np.random.randint(0,3,(2,3))
print(p,q,sep='\n')

[[1 1]
 [2 2]
 [2 0]]
[[2 2 2]
 [1 1 0]]


In [13]:
p[:,1]

array([1, 2, 0])

In [14]:
np.dot(p, q)

array([[3, 3, 2],
       [6, 6, 4],
       [4, 4, 4]])

## Angle between 2 vectors using dot product

In [43]:
def angle_between(v1, v2):
    dot_pr = v1.dot(v2)
    norms = np.linalg.norm(v1) * np.linalg.norm(v2)
    return np.rad2deg(np.arccos(dot_pr / norms))

p = np.random.randint(1,3,(3,))
q = np.random.randint(1,3,(3,))
print(p,q,angle_between(p, q),sep='\n')

[2 1 1]
[1 1 1]
19.471220634490674


In [40]:
v.shape

(3,)

## Multiplication of incompatible matrices

In [15]:
p = np.random.randint(0,3,(3,2))
q = np.random.randint(0,3,(3,3))
print(p,q,sep='\n')

[[2 2]
 [2 1]
 [2 0]]
[[2 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
np.dot(p, q)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

# Cross product

## Of 2 vectors

In [17]:
p = np.random.randint(0,9,(3))
q = np.random.randint(0,9,(3))
print(p,q,sep='\n')

[1 7 2]
[7 0 4]


In [18]:
np.cross(p, q)

array([ 28,  10, -49])

# Determinant of matrice

## 2 by 2

In [19]:
p = np.random.randint(0,9,(2,2))
p

array([[3, 3],
       [8, 6]])

In [20]:
np.linalg.det(p)

-6.0

## 3 by 3

In [24]:
p = np.random.randint(0,9,(3,3))
p

array([[2, 5, 6],
       [1, 7, 0],
       [7, 2, 3]])

In [25]:
np.linalg.det(p)

-254.99999999999991

# Inverse of matrice

In [21]:
p = np.random.randint(0,9,(3,3))
p

array([[4, 3, 6],
       [6, 6, 7],
       [1, 7, 6]])

In [22]:
np.linalg.inv(p)

array([[-0.16883117,  0.31168831, -0.19480519],
       [-0.37662338,  0.23376623,  0.1038961 ],
       [ 0.46753247, -0.32467532,  0.07792208]])

# Magnitude of vector

In [24]:
p = np.random.randint(0,9,(3,1))
print(p)

[[7]
 [0]
 [1]]


In [26]:
np.linalg.norm(p)

7.0710678118654755

# Unit vector

In [34]:
def unit_vector(v):
    return v / np.linalg.norm(v)

p = np.random.randint(0,9,(3,1))

print(p, unit_vector(p), sep='\n')

[[5]
 [7]
 [1]]
[[0.57735027]
 [0.80829038]
 [0.11547005]]


# Matrix transpose

In [44]:
A = np.matrix([
    [3, 4],
    [1, 0]
])
A.T

matrix([[3, 1],
        [4, 0]])

# Polynomial

## Generation using coefficients - Ax^2 + Bx + C

In [37]:
p = np.poly1d([1,-3,2])
print(p)

   2
1 x - 3 x + 2


## Generation using roots - (X-A)(X-B)(X-C)

In [38]:
p2 = np.poly1d([1, 2], True)
print(p2)

   2
1 x - 3 x + 2


## Evaluation of polynomial

In [39]:
p(0.5)

0.75

## Determine roots of polynomial

In [40]:
p.roots

array([2., 1.])

## Show coefficients of polynomial

In [41]:
p.c

array([ 1, -3,  2])

In [42]:
# Show coefficient of kth power
p[1]

-3

## Arithmetic operations on polynomials

In [43]:
p*p

poly1d([  1,  -6,  13, -12,   4])

In [44]:
p/p

(poly1d([1.]), poly1d([0.]))

In [45]:
(p**3 + 4) / p

(poly1d([  1.,  -6.,  13., -12.,   4.]), poly1d([4.]))

# Vectorized functions
Apply arithmetic operations row-wise in a vector format

In [46]:
def addsubtract(a, b):
    if a > b:
        return a - b
    else:
        return a + b

In [47]:
vec_addsubtract = np.vectorize(addsubtract)

In [48]:
vec_addsubtract([0,3,6,9],[1,3,5,7])

array([1, 6, 1, 2])

# Integration

In [50]:
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
result

(1.1178179380783244, 7.866317216380707e-09)

\[I(a,b)=\int_{0}^{1} ax^2+b \, dx.\]

In [55]:
# from scipy.integrate import quad

def integrand(x, a, b):
    return a*x**2 + b

a = 2
b = 1
I = integrate.quad(integrand, 0, 1, args=(a,b))
I

(1.6666666666666667, 1.8503717077085944e-14)

# Differential equation

# Numpy Remaining concepts

Einstein's summation convention of two given multidimensional arrays

compute the outer product of two given vectors

compute the inner product of vectors for 1-D arrays

compute the eigenvalues and right eigenvectors of a given square array

compute the Kronecker product of two given mulitdimension arrays

compute the condition number of a given matrix

find a matrix or vector norm

calculate the QR decomposition of a given matrix

compute the condition number of a given matrix

get the lower-triangular L in the Cholesky decomposition of a given array

get the qr factorization of a given arrays

compute the factor of a given array by Singular Value Decomposition

calculate the Frobenius norm and the condition number of a given arrays

# SciPy Remaining concepts

import files from MATLAB (.mat)